### ISSUE TITLE
[feat]: Adding Percentage (%) Feature to the Calculator

### ISSUE THREAD

**Issue by purnasth** [Surajit0573/Calculator#15]
# Issue Title: Adding Percentage (%) Feature to the Calculator

## Issue Description:
I propose the addition of a percentage (%) feature to the existing calculator web application. This enhancement will provide users with the ability to perform percentage calculations, making the calculator more versatile and user-friendly.

## Proposed Changes:
1. **Percentage (%) Feature**: Implement the percentage feature, allowing users to calculate percentages of numbers easily. The feature should be accessible and intuitive for users.

## Rationale:
The addition of the percentage (%) feature is essential for the following reasons:

### Enhanced Functionality:
The percentage feature expands the calculator's capabilities, enabling users to calculate percentages, which is a common and valuable calculation in various scenarios.

### Improved User Experience:
This addition enhances the user experience, making the calculator more functional and user-friendly.

## Additional Information (if available):
If specific guidelines or steps are required for implementing this feature, please provide the necessary information. I am committed to adding the percentage feature effectively and in line with project requirements.

**Comment by Harrshhpattell** [comment]
I want to work on this issue can u assign me under hacktoberfest label
