### ISSUE TITLE
Add new functional buttons in the calculator.

### ISSUE THREAD

**Issue by Surajit0573** [Surajit0573/Calculator#17]
Add these 4 buttons (must) ...

- Power (^): Calculates a number raised to a specified power. (ex :- 2^3 = 8)
- Modulo (%): Computes the remainder of a division operation. (ex:- 15%4 = 3)
- Square Root (√): Finds the square root of a number. (ex:- √25 = 5)
- Logarithm (log): Calculates the logarithm of a number. (ex:- log 10 = 1)

You can add other buttons, but they should be working. **Keep the overall design in mind.**

**Comment by cyberdad68** [comment]
i would like to work on this issue,Could you assign me this.

**Comment by KunalDhand** [comment]
I can do this for you. Kindly assign this to me.

**Comment by KunalDhand** [comment]
Checkout the following purposed solution @Surajit0573 . Everything is working, just need to enclose sqrt and ln functions in round brackets "( )" to make them work.
Let me know, what you think about it. I will make a pull request once you are satisfied.
![purposed solution calculator](https://github.com/Surajit0573/Calculator/assets/99679283/bdfff987-65df-434d-8a09-02e629621ed7)

**Comment by Surajit0573** [comment]
@kunaldhand Looks very good. Can you just add a clear button (in between "C" and "7") which will delete one digit/operand at a time?

**Comment by KunalDhand** [comment]
check please @Surajit0573 
![purposed solution calculator2](https://github.com/Surajit0573/Calculator/assets/99679283/d1cd9f74-bf74-420a-a7bf-c035fe8712e2)

**Comment by Surajit0573** [comment]
You can create a PR now!!
