### ISSUE TITLE
Add new Buttons

### ISSUE THREAD

**Issue by Surajit0573** [Surajit0573/Calculator#8]
Add new Buttons in this calculator like power, modulo, root, log,... etc.
Keep the overall design in mind.

**Comment by gurjott** [comment]
please assign me

**Comment by ZainabR11** [comment]
I have recently created calculator . You can check my repo. I want to contribute to this issue . Kindly assign this issue to me. I would love to contribute to this. @Surajit0573  . I want to contribute for hacktoberfest 2023 .

**Comment by ZainabR11** [comment]
Thankyou for assigning. @Surajit0573

**Comment by ZainabR11** [comment]
Sir can you please help me actually  I have deleted my forked repo and I forked it again and try to pull request but there is an error occurring. I tried to sync fork but I got confused. Can you please assist now what I have to do?

**Comment by ZainabR11** [comment]
@Surajit0573

**Comment by ZainabR11** [comment]
Will this effect my hacktoberfest contribution?
